version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: cmd/http/Dockerfile
    container_name: http-server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - chatapp-network

  ws:
    build:
      context: .
      dockerfile: cmd/ws/Dockerfile
    container_name: ws-server
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - chatapp-network

  db:
    image: postgres:17-alpine
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge

volumes:
  pgdata:
