name: Build Artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: download dependencies
        run: go mod download

      - name: run unit test
        run: go test ./...  -v -cover

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cmd/ws/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chat-app-ws:latest
